package errors_test

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"

	caos_errs "github.com/zitadel/zitadel/internal/errors"
)

func Test{{.ErrorName}}Error(t *testing.T) {
	var err interface{}
	err = new(caos_errs.{{.ErrorName}}Error)
	_, ok := err.(*caos_errs.{{.ErrorName}})
	assert.True(t, ok)
}

func TestThrow{{.ErrorName}}f(t *testing.T) {
	err := caos_errs.Throw{{.ErrorName}}f(nil, "id", "msg")
	_, ok := err.(*caos_errs.{{.ErrorName}}Error)
	assert.True(t, ok)
}

func TestIs{{.ErrorName}}(t *testing.T) {
	err := caos_errs.Throw{{.ErrorName}}(nil, "id", "msg")
	ok := caos_errs.Is{{.ErrorName}}(err)
	assert.True(t, ok)

	err = errors.New("I am found!")
	ok = caos_errs.Is{{.ErrorName}}(err)
	assert.False(t, ok)
}
